blank_issues_enabled: true
contact_links:
  - name: Documentation
    about: Find tutorials, use cases, and guides in the AgentRadis documentation.
    url: https://github.com/scooter-lacroix/AgentRadis/wiki
