# Testing configuration for AgentRadis

# Default active language model
active_llm: lm_studio

# LLM Settings
llm_settings:
  lm_studio:
    api_type: local
    model: gemma-3-4b-it-Q8_0.ggufF
    api_base: http://127.0.0.1:1234/v1
    api_key: lm-studio
    model_path: "/media/stan/Lin Stor/Models/models/lmstudio-community/gemma-3-4b-it-GGUF/gemma-3-4b-it-Q8_0.gguf"
    temperature: 0.7
    max_tokens: 8048
  
  gpt-4-turbo:
    api_type: openai
    model: gpt-4-1106-preview
    fallback_model: gpt-3.5-turbo
    api_key: test-key-123
  
  mistral-medium:
    api_type: mistral
    model: mistral-medium
    fallback_model: mistral-small
    api_key: test-key-123
  
  anthropic:
    api_type: anthropic
    model: claude-2
    fallback_model: claude-instant-1
    api_key: test-key-123

# Browser configuration
browser:
  headless: true
  executable_path: null

# Logging configuration
logging:
  level: INFO
  file_path: logs/radis.log
  max_file_size: 10485760
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
